### PR TITLE
Fix Doc for API_ENDPOINT Configuration

### PR DESCRIPTION
**Pull request by oliver-schoenherr**
Fix outdated Documentation.

### CODE REVIEW

**Comment by tvollmer-at-is24** [comment]
Maybe it would be good to have a "configuration" file, to enable the Admin to easily configure the system. Instead of looking for the Variable in the source code.

**Comment by schlomo** [comment]
+1 for incremental improvement :-)

**Comment by esc** [comment]
I vote for merge, who will click the button?

**Comment by schlomo** [comment]
Usually the first co-author who looked at the change retains the right/duty to merge it. Or he asks somebody else to take over.

**Comment by esc** [comment]
@schlomo I don't think there is a "usually" in this case, but what you say sounds reasonable. We could also look at something like:

http://rfc.zeromq.org/spec:16

For now, perhaps we should agree on the following simple rules:
- pull-requests are responded to with the actions: merge, comment or reject
- pull-requests can be merged on a first-come first-serve basis
- you never merge your own pull-requests 
- if something broken was merged in a pull-request, another pull-request must be made to fix it

**Comment by esc** [comment]
Having said that, here goes!

**Comment by SebastianStiehl** [comment]
I didn't noticed that there was a documentation for the variable as i moved it. The Documentation is still not valid. There is not longer a global called AFP_API_ENDPOINT. It's now part of a angular constant service appVars with the key afpApiEndpoint. I can fix this on Monday.

For me the app.js is the configuration of the angular app. It defines the main module, the constants and the config. But we could move the constant service definition in a separate file if this helps to administrate it.

**Pull request merged**
